const API='https://equran.id/api/v2';
const q=new URLSearchParams(location.search);
const sid=Math.min(114,Math.max(1,parseInt(q.get('surah')||'1',10)||1));
const targetAyat=parseInt(q.get('ayat')||'0',10)||0;
const BATCH=10;
let data=null,rendered=0,arabSize=46,activeAyat=0;
const $=id=>document.getElementById(id);
const qariNames={'01':'Abdullah Al-Juhany','02':'Abdul Muhsin Al-Qasim','03':'Abdurrahman As-Sudais','04':'Ibrahim Al-Dossari','05':'Misyari Rasyid Al-Afasy','06':'Yasser Al-Dosari'};
function icons(){if(window.lucide)lucide.createIcons()}
function typeLabel(x){return String(x||'').toLowerCase()==='mekah'?'Makkiyah':'Madaniyah'}
function glyph(id){return`surah${String(id).padStart(3,'0')}`}
function verseAudio(v){const a=v.audio||{};return a[$('qariSelect').value]||a['05']||Object.values(a)[0]||''}
function setHeader(d){document.title=`${d.namaLatin} — Al-Qur'an Liputan6`;$('surahNumber').textContent='SURAH '+String(d.nomor).padStart(2,'0');$('surahName').textContent=d.namaLatin;$('surahMeta').textContent=`${d.arti} · ${d.jumlahAyat} Ayat · ${typeLabel(d.tempatTurun)}`;$('crumbName').textContent=d.namaLatin;$('surahArabic').textContent=glyph(d.nomor);$('apiStatus').querySelector('span:last-child').textContent=`Data asli · ${d.jumlahAyat} ayat · audio ${qariNames[$('qariSelect').value]}`}
function ayahMarkup(v){return `<article class="ayah" id="ayat-${v.nomorAyat}"><div class="ayah-head"><div class="ayah-number">${v.nomorAyat}</div><div class="ayah-actions"><button class="ayah-action" type="button" data-play="${v.nomorAyat}"><i data-lucide="play"></i>Audio</button><button class="ayah-action" type="button" data-save="${v.nomorAyat}"><i data-lucide="bookmark"></i>Simpan</button><button class="ayah-action" type="button" data-share="${v.nomorAyat}"><i data-lucide="share-2"></i>Bagikan</button><a class="ayah-action detail" href="./ayat.html?surah=${sid}&ayat=${v.nomorAyat}"><i data-lucide="book-open-text"></i>Detail</a></div></div><div class="ayah-ar" lang="ar" dir="rtl" style="font-size:${arabSize}px">${v.teksArab}</div><div class="ayah-latin">${v.teksLatin||''}</div><p class="ayah-translation">${v.teksIndonesia||''}</p></article>`}
function renderBatch(){if(!data||rendered>=data.ayat.length)return;const end=Math.min(rendered+BATCH,data.ayat.length);$('ayahList').insertAdjacentHTML('beforeend',data.ayat.slice(rendered,end).map(ayahMarkup).join(''));rendered=end;updateLoadMore();icons()}
function updateLoadMore(){const wrap=$('loadMoreWrap'),btn=$('loadMoreAyat');if(!data||rendered>=data.ayat.length){wrap.hidden=true;return}const remaining=data.ayat.length-rendered;btn.textContent=`Tampilkan ${Math.min(BATCH,remaining)} Ayat Berikutnya`;wrap.hidden=false}
function ensureRendered(n){while(data&&rendered<n&&rendered<data.ayat.length)renderBatch()}
function setupNav(d){if(d.suratSebelumnya&&typeof d.suratSebelumnya==='object'){$('prevSurah').href=`./surah.html?surah=${d.suratSebelumnya.nomor}`;$('prevName').textContent=d.suratSebelumnya.namaLatin}else $('prevSurah').hidden=true;if(d.suratSelanjutnya&&typeof d.suratSelanjutnya==='object'){$('nextSurah').href=`./surah.html?surah=${d.suratSelanjutnya.nomor}`;$('nextName').textContent=d.suratSelanjutnya.namaLatin}else $('nextSurah').hidden=true}
function markPlaying(n){ensureRendered(n);document.querySelectorAll('.ayah').forEach(x=>x.classList.remove('is-playing'));document.getElementById('ayat-'+n)?.classList.add('is-playing');activeAyat=n;localStorage.setItem('l6q-last',JSON.stringify({surah:sid,ayat:n,name:data?.namaLatin||''}))}
function syncPlayState(playing){$('playFull').innerHTML=`<i data-lucide="${playing?'pause':'play'}"></i><span>${playing?'Jeda':'Putar Surah'}</span>`;$('playFull').setAttribute('aria-pressed',playing?'true':'false');icons()}
function playAyat(n){const v=data?.ayat?.find(x=>x.nomorAyat===n);if(!v)return;const src=verseAudio(v);if(!src)return;$('audioEl').src=src;$('audioTitle').textContent=`${data.namaLatin} · Ayat ${n}`;$('audioSub').textContent=qariNames[$('qariSelect').value];$('audioDock').hidden=false;markPlaying(n);$('audioEl').play();$('audioToggle').innerHTML='<i data-lucide="pause"></i>';syncPlayState(false);icons()}
function playSurah(){const full=data?.audioFull||{};const src=full[$('qariSelect').value]||full['05']||Object.values(full)[0];if(!src){playAyat(1);return}const audio=$('audioEl'),same=audio.src===src||audio.currentSrc===src;if(same&&!audio.paused){audio.pause();syncPlayState(false);$('audioToggle').innerHTML='<i data-lucide="play"></i>';icons();return}if(!same)audio.src=src;$('audioTitle').textContent=data.namaLatin+' · Surah lengkap';$('audioSub').textContent=qariNames[$('qariSelect').value];$('audioDock').hidden=false;audio.play();syncPlayState(true);$('audioToggle').innerHTML='<i data-lucide="pause"></i>';icons()}
function saveAyat(n){localStorage.setItem(`l6q-bookmark-${sid}-${n}`,'1');document.querySelector(`[data-save="${n}"]`)?.classList.add('active')}
async function shareAyat(n){const v=data?.ayat?.find(x=>x.nomorAyat===n);if(!v)return;const url=new URL(`./ayat.html?surah=${sid}&ayat=${n}`,location.href).href;const text=`${data.namaLatin} ${n}\n${v.teksArab}\n${v.teksIndonesia}`;try{if(navigator.share)await navigator.share({title:`${data.namaLatin} ayat ${n}`,text,url});else await navigator.clipboard.writeText(text)}catch(e){}}
async function load(){try{const r=await fetch(`${API}/surat/${sid}`);if(!r.ok)throw new Error('surat');const j=await r.json();data=j.data;setHeader(data);$('ayatJump').innerHTML='<option value="">Pilih ayat</option>'+data.ayat.map(v=>`<option value="${v.nomorAyat}">Ayat ${v.nomorAyat}</option>`).join('');$('ayahList').innerHTML='';renderBatch();setupNav(data);localStorage.setItem('l6q-last',JSON.stringify({surah:sid,ayat:targetAyat||1,name:data.namaLatin}));if(targetAyat){ensureRendered(targetAyat);setTimeout(()=>document.getElementById('ayat-'+targetAyat)?.scrollIntoView({behavior:'smooth',block:'start'}),180)}}catch(e){$('apiStatus').querySelector('span:last-child').textContent='Data Al-Qur\'an belum dapat dimuat.';$('apiStatus').querySelector('.source-dot').style.background='#ef4444';$('ayahList').innerHTML='<div class="reader-loading">Silakan periksa koneksi dan coba lagi.</div>'}}
$('loadMoreAyat').onclick=()=>{const btn=$('loadMoreAyat');btn.disabled=true;btn.textContent='Memuat...';requestAnimationFrame(()=>{renderBatch();btn.disabled=false})};
$('fontDown').onclick=()=>{arabSize=Math.max(38,arabSize-2);document.querySelectorAll('.ayah-ar').forEach(x=>x.style.fontSize=arabSize+'px')};
$('fontUp').onclick=()=>{arabSize=Math.min(60,arabSize+2);document.querySelectorAll('.ayah-ar').forEach(x=>x.style.fontSize=arabSize+'px')};
$('playFull').onclick=playSurah;
$('qariSelect').onchange=()=>{if(data)$('apiStatus').querySelector('span:last-child').textContent=`Data asli · ${data.jumlahAyat} ayat · audio ${qariNames[$('qariSelect').value]}`};
$('ayatJump').onchange=e=>{const n=+e.target.value;if(!n)return;ensureRendered(n);requestAnimationFrame(()=>document.getElementById('ayat-'+n)?.scrollIntoView({behavior:'smooth',block:'start'}));history.replaceState(null,'',`./surah.html?surah=${sid}&ayat=${n}`);localStorage.setItem('l6q-last',JSON.stringify({surah:sid,ayat:n,name:data?.namaLatin||''}))};
$('ayahList').addEventListener('click',e=>{const p=e.target.closest('[data-play]'),s=e.target.closest('[data-save]'),sh=e.target.closest('[data-share]');if(p)playAyat(+p.dataset.play);if(s)saveAyat(+s.dataset.save);if(sh)shareAyat(+sh.dataset.share)});
$('audioToggle').onclick=()=>{const a=$('audioEl');if(a.paused){a.play();$('audioToggle').innerHTML='<i data-lucide="pause"></i>';if(($('audioTitle').textContent||'').includes('Surah lengkap'))syncPlayState(true)}else{a.pause();$('audioToggle').innerHTML='<i data-lucide="play"></i>';syncPlayState(false)}icons()};
$('audioClose').onclick=()=>{$('audioEl').pause();$('audioDock').hidden=true;syncPlayState(false)};
$('audioEl').ontimeupdate=()=>{$('audioProgress').style.width=($('audioEl').duration?$('audioEl').currentTime/$('audioEl').duration*100:0)+'%'};
$('audioEl').onended=()=>{syncPlayState(false);if(activeAyat&&data&&activeAyat<data.jumlahAyat)playAyat(activeAyat+1)};
document.addEventListener('DOMContentLoaded',()=>{icons();load()});